# Generated by Django 5.2.1 on 2025-06-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('endereco', models.CharField(max_length=50)),
                ('dt_ultima_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('item', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='estoque.item')),
            ],
        ),
    ]
