# Generated by Django 5.2.3 on 2025-06-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoque',
            name='item',
        ),
        migrations.AddField(
            model_name='estoque',
            name='id_item',
            field=models.UUIDField(null=True),
        ),
    ]
