# Generated by Django 5.2.1 on 2025-05-15 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('endereco', models.CharField(max_length=50)),
                ('item', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='estoque.item')),
            ],
        ),
    ]
