# Generated by Django 5.2.1 on 2025-06-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_item_quantidade_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unid_medida',
        ),
        migrations.AddField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='saldo_estoque',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
