# Generated by Django 5.2.3 on 2025-06-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_estoque_item_estoque_id_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
