# Generated by Django 5.2.1 on 2025-06-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_remove_item_unid_medida_item_descricao_item_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='saldo_estoque',
        ),
    ]
