# Generated by Django 5.2.3 on 2025-06-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_estoque_id_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='id_item',
            field=models.IntegerField(null=True),
        ),
    ]
